### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\User\Desktop\oqlwgq\main.py", line 1, in <module>     import requests ModuleNotFoundError: No module named 'requests' >>> 

### ISSUE THREAD

**Issue by arbidolsss** [imvast/Discord-Account-Gen#12]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\oqlwgq\main.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>>

**Comment by Woosh9129** [comment]
pip install requests
py main.py

**Comment by imvast** [comment]
discord.gg/vast to buy
