### ISSUE TITLE
  function 'SetsConsoleMode' not found

### ISSUE THREAD

**Issue by lazpap11** [imvast/Discord-Account-Gen#14]
when i run the python main.py command it responds with the title

**Comment by Lamer0001** [comment]
AttributeError: function 'SetsConsoleMode' not found. Did you mean: 'GetConsoleMode'?

**Comment by imvast** [comment]
update ur python vers

**Comment by letruxux** [comment]
> update ur python vers

to 3.11? i'm on 3.10 now
